spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: "12345"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true